# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-08 20:14
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
        ('layer', '0002_auto_20180908_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='categories',
            field=models.ManyToManyField(blank=True, to='search.Category'),
        ),
        migrations.AddField(
            model_name='layer',
            name='ts_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
