# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-08 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0004_auto_20180908_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='textsearchable_index',
            new_name='ts_index',
        ),
    ]
